global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
    - channel: '#alerts'
